import 'package:image_picker/image_picker.dart';
import 'package:kodisha_flutter/models/house_model.dart';
import 'package:kodisha_flutter/models/utility_model.dart';

/// The base contract for any data intent generated by a form.
sealed class ActionInput {}

class LoginInput extends ActionInput {
  LoginInput({required this.email, required this.password});
  final String email;
  final String password;
}

class FormSubmitInput extends ActionInput {
  FormSubmitInput({required this.formType, required this.payload, this.id});
  final String formType;
  final Map<String, dynamic> payload; 
  final int? id;
}

class CreateHouseInput extends ActionInput {
  CreateHouseInput({
    required this.houseName,
    required this.estateId,
    required this.images,
    required this.houseType,
    required this.isAvailable,
    this.utilities,
  });
  final String houseName;
  final IsOccupied isAvailable;
  final int estateId;
  final List<XFile>? images;
  final HouseType houseType;
  final List<UtilityModel>? utilities;
}

class NewEstateInput extends ActionInput {
  NewEstateInput({required this.name, required this.location, this.image});
  final String location;
  final String name;
  final XFile? image;
}